### ISSUE TITLE
I need to have Python installed on my computer?

### ISSUE THREAD

**Issue by Jaylton** [wulfebw/mergevec#2]
I need to have Python installed on my computer? if so where do I download? thank you!

**Comment by marksabbath** [comment]
Yes @Jaylton you need to install Python on your machine. You should be able to find the proper version for your O.S. here https://www.python.org/downloads/

**Comment by Jaylton** [comment]
when I run, I showed this error

Traceback (most recent call last):
  File "./tools/mergevec.py", line 170, in <module>
    merge_vec_files(vec_directory, output_filename)
  File "./tools/mergevec.py", line 120, in merge_vec_files
    val = struct.unpack('<iihh', content[:12])
TypeError: a bytes-like object is required, not 'str'

do you know why? how can I solve?
@marksabbath, você é brasileiro?

**Comment by thacoon** [comment]
@Jaylton you need to install _Python2_ I guess. If you want to use _Python3_ instead, try [my fork](https://github.com/thacoon/mergevec) instead, it should work with your Python version.

**Comment by Jaylton** [comment]
worked, thank you
